// <auto-generated />
using System;
using MAVE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAVE.Migrations
{
    [DbContext(typeof(DbAa60a4MavetestContext))]
    [Migration("20260921213736_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MAVE.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ARTICLE", (string)null);
                });

            modelBuilder.Entity("MAVE.Models.Auditory", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.ToTable("AUDITORY", (string)null);
                });

            modelBuilder.Entity("MAVE.Models.CatArticleType", b =>
                {
                    b.Property<short>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TypeId"));

                    b.Property<string>("ArticleType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nchar(120)")
                        .IsFixedLength();

                    b.HasKey("TypeId");

                    b.ToTable("CAT_ARTICLE_TYPE", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = (short)1,
                            ArticleType = "Artículo"
                        },
                        new
                        {
                            TypeId = (short)2,
                            ArticleType = "Video"
                        },
                        new
                        {
                            TypeId = (short)3,
                            ArticleType = "Podcast"
                        },
                        new
                        {
                            TypeId = (short)4,
                            ArticleType = "Ejercicio"
                        });
                });

            modelBuilder.Entity("MAVE.Models.CatEvaluation", b =>
                {
                    b.Property<short>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("EvaluationId"));

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EvaluationId");

                    b.ToTable("CAT_EVALUATION", (string)null);

                    b.HasData(
                        new
                        {
                            EvaluationId = (short)1,
                            Result = "Sin evaluación"
                        },
                        new
                        {
                            EvaluationId = (short)2,
                            Result = "Dominante"
                        },
                        new
                        {
                            EvaluationId = (short)3,
                            Result = "Influyente"
                        },
                        new
                        {
                            EvaluationId = (short)4,
                            Result = "Estable"
                        },
                        new
                        {
                            EvaluationId = (short)5,
                            Result = "Concienzudo"
                        });
                });

            modelBuilder.Entity("MAVE.Models.CatOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("Abcd")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<short>("CatQuestionId")
                        .HasColumnType("smallint");

                    b.Property<string>("EvaOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasKey("OptionId");

                    b.HasIndex("CatQuestionId");

                    b.ToTable("CAT_OPTION", (string)null);

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Abcd = "A",
                            CatQuestionId = (short)1,
                            EvaOption = "Amable, gentil",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 2,
                            Abcd = "B",
                            CatQuestionId = (short)1,
                            EvaOption = "Persuasivo, convincente",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 3,
                            Abcd = "C",
                            CatQuestionId = (short)1,
                            EvaOption = "Humilde, reservado, modesto",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 4,
                            Abcd = "D",
                            CatQuestionId = (short)1,
                            EvaOption = "Original, innovador, diferente",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 5,
                            Abcd = "A",
                            CatQuestionId = (short)2,
                            EvaOption = "Atractivo, simpático, agradable para los demás",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 6,
                            Abcd = "B",
                            CatQuestionId = (short)2,
                            EvaOption = "Cooperativo, está de acuerdo con frecuencia",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 7,
                            Abcd = "C",
                            CatQuestionId = (short)2,
                            EvaOption = "Terco, tenaz, combativo",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 8,
                            Abcd = "D",
                            CatQuestionId = (short)2,
                            EvaOption = "Dulce, complaciente",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 9,
                            Abcd = "A",
                            CatQuestionId = (short)3,
                            EvaOption = "Fácil de guiar, seguidor",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 10,
                            Abcd = "B",
                            CatQuestionId = (short)3,
                            EvaOption = "Directo, retador",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 11,
                            Abcd = "C",
                            CatQuestionId = (short)3,
                            EvaOption = "Leal, devoto, fiel",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 12,
                            Abcd = "D",
                            CatQuestionId = (short)3,
                            EvaOption = "Encantador, hace que la gente disfrute",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 13,
                            Abcd = "A",
                            CatQuestionId = (short)4,
                            EvaOption = "Abierto de mente, receptivo",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 14,
                            Abcd = "B",
                            CatQuestionId = (short)4,
                            EvaOption = "Considerado, gusta de ayudar",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 15,
                            Abcd = "C",
                            CatQuestionId = (short)4,
                            EvaOption = "Voluntarioso, carácter fuerte y decidido",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 16,
                            Abcd = "D",
                            CatQuestionId = (short)4,
                            EvaOption = "Alegre, divertido",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 17,
                            Abcd = "A",
                            CatQuestionId = (short)5,
                            EvaOption = "Jovial, bromista",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 18,
                            Abcd = "B",
                            CatQuestionId = (short)5,
                            EvaOption = "Preciso, exacto",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 19,
                            Abcd = "C",
                            CatQuestionId = (short)5,
                            EvaOption = "Decidido, determinado, audaz",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 20,
                            Abcd = "D",
                            CatQuestionId = (short)5,
                            EvaOption = "Estable, de temperamento tranquilo, calmado",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 21,
                            Abcd = "A",
                            CatQuestionId = (short)6,
                            EvaOption = "Competitivo, busca ganar",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 22,
                            Abcd = "B",
                            CatQuestionId = (short)6,
                            EvaOption = "Considerado, cariñoso, tiene mucho tacto",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 23,
                            Abcd = "C",
                            CatQuestionId = (short)6,
                            EvaOption = "Extrovertido, le encanta la diversión",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 24,
                            Abcd = "D",
                            CatQuestionId = (short)6,
                            EvaOption = "Armonioso, busca el acuerdo",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 25,
                            Abcd = "A",
                            CatQuestionId = (short)7,
                            EvaOption = "Exigente, difícil de satisfacer",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 26,
                            Abcd = "B",
                            CatQuestionId = (short)7,
                            EvaOption = "Obediente, hace lo que se le instruye que haga",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 27,
                            Abcd = "C",
                            CatQuestionId = (short)7,
                            EvaOption = "Tenaz y decidido, determinado",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 28,
                            Abcd = "D",
                            CatQuestionId = (short)7,
                            EvaOption = "Bromista, juguetón, divertido",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 29,
                            Abcd = "A",
                            CatQuestionId = (short)8,
                            EvaOption = "Valiente, temerario, lleno de coraje",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 30,
                            Abcd = "B",
                            CatQuestionId = (short)8,
                            EvaOption = "Inspirador, estimulante, motivador",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 31,
                            Abcd = "C",
                            CatQuestionId = (short)8,
                            EvaOption = "Obediente, no confrontas, cede fácilmente",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 32,
                            Abcd = "D",
                            CatQuestionId = (short)8,
                            EvaOption = "Tímido, aprehensivo, callado",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 33,
                            Abcd = "A",
                            CatQuestionId = (short)9,
                            EvaOption = "Sociable, disfruta de la compañía de otros",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 34,
                            Abcd = "B",
                            CatQuestionId = (short)9,
                            EvaOption = "Paciente, estable, tolerante",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 35,
                            Abcd = "C",
                            CatQuestionId = (short)9,
                            EvaOption = "Autosuficiente, independiente",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 36,
                            Abcd = "D",
                            CatQuestionId = (short)9,
                            EvaOption = "De bajo perfil, tibio, reservado",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 37,
                            Abcd = "A",
                            CatQuestionId = (short)10,
                            EvaOption = "De bajo perfil, tibio, reservado",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 38,
                            Abcd = "B",
                            CatQuestionId = (short)10,
                            EvaOption = "Receptivo, abierto a sugerencias",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 39,
                            Abcd = "C",
                            CatQuestionId = (short)10,
                            EvaOption = "Cordial, cálido, amistoso",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 40,
                            Abcd = "D",
                            CatQuestionId = (short)10,
                            EvaOption = "Moderado, evita los extremos",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 41,
                            Abcd = "A",
                            CatQuestionId = (short)11,
                            EvaOption = "Expresivo, habla mucho",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 42,
                            Abcd = "B",
                            CatQuestionId = (short)11,
                            EvaOption = "Controlado, poco expresivo",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 43,
                            Abcd = "C",
                            CatQuestionId = (short)11,
                            EvaOption = "Convencional, sistemático, rutinario",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 44,
                            Abcd = "D",
                            CatQuestionId = (short)11,
                            EvaOption = "Decidido, cierto, firme al tomar decisiones",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 45,
                            Abcd = "A",
                            CatQuestionId = (short)12,
                            EvaOption = "Refinado, elegante al hablar",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 46,
                            Abcd = "B",
                            CatQuestionId = (short)12,
                            EvaOption = "Busca retos, toma riesgos",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 47,
                            Abcd = "C",
                            CatQuestionId = (short)12,
                            EvaOption = "Diplomático, tiene tacto con las personas",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 48,
                            Abcd = "D",
                            CatQuestionId = (short)12,
                            EvaOption = "Satisfecho, contento, cómodo",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 49,
                            Abcd = "A",
                            CatQuestionId = (short)13,
                            EvaOption = "Agresivo, desafiante, enfocado a la acción",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 50,
                            Abcd = "B",
                            CatQuestionId = (short)13,
                            EvaOption = "Alma de la fiesta, entretenido, extrovertido",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 51,
                            Abcd = "C",
                            CatQuestionId = (short)13,
                            EvaOption = "Ingenuo, es fácil que se aprovechen de él",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 52,
                            Abcd = "D",
                            CatQuestionId = (short)13,
                            EvaOption = "Temeroso, tiende a preocuparse mucho",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 53,
                            Abcd = "A",
                            CatQuestionId = (short)14,
                            EvaOption = "Cuidadoso, desconfiado, cauteloso",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 54,
                            Abcd = "B",
                            CatQuestionId = (short)14,
                            EvaOption = "Determinado, decidido, se para firme",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 55,
                            Abcd = "C",
                            CatQuestionId = (short)14,
                            EvaOption = "Convincente, transmite seguridad",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 56,
                            Abcd = "D",
                            CatQuestionId = (short)14,
                            EvaOption = "De buen carácter, cortés, gusta de satisfacer",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 57,
                            Abcd = "A",
                            CatQuestionId = (short)15,
                            EvaOption = "Entusiasta, le pone ganas",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 58,
                            Abcd = "B",
                            CatQuestionId = (short)15,
                            EvaOption = "Impaciente, ansioso, desesperado a veces",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 59,
                            Abcd = "C",
                            CatQuestionId = (short)15,
                            EvaOption = "Amistoso, logra acuerdos, acepta",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 60,
                            Abcd = "D",
                            CatQuestionId = (short)15,
                            EvaOption = "Energético, vivaz, entusiasta",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 61,
                            Abcd = "A",
                            CatQuestionId = (short)16,
                            EvaOption = "Tiene autoconfianza, cree en sí mismo, seguro",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 62,
                            Abcd = "B",
                            CatQuestionId = (short)16,
                            EvaOption = "Comprensivo, compasivo, apoyador de la gente",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 63,
                            Abcd = "C",
                            CatQuestionId = (short)16,
                            EvaOption = "Tolerante",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 64,
                            Abcd = "D",
                            CatQuestionId = (short)16,
                            EvaOption = "Asertivo, agresivo, directo",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 65,
                            Abcd = "A",
                            CatQuestionId = (short)17,
                            EvaOption = "Muy disciplinado, auto controlado",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 66,
                            Abcd = "B",
                            CatQuestionId = (short)17,
                            EvaOption = "Generoso, le gusta compartir",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 67,
                            Abcd = "C",
                            CatQuestionId = (short)17,
                            EvaOption = "Animado, expresivo, usa muchos gestos",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 68,
                            Abcd = "D",
                            CatQuestionId = (short)17,
                            EvaOption = "Persistente, no da paso atrás, se niega a perder",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 69,
                            Abcd = "A",
                            CatQuestionId = (short)18,
                            EvaOption = "Admirable, digno de reconocimiento",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 70,
                            Abcd = "B",
                            CatQuestionId = (short)18,
                            EvaOption = "Amable, deseoso de ayudar y de compartir",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 71,
                            Abcd = "C",
                            CatQuestionId = (short)18,
                            EvaOption = "Resignado, renuncia, no lucha",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 72,
                            Abcd = "D",
                            CatQuestionId = (short)18,
                            EvaOption = "Fuerte de carácter, poderoso",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 73,
                            Abcd = "A",
                            CatQuestionId = (short)19,
                            EvaOption = "Respetuoso, trata con consideración a las personas",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 74,
                            Abcd = "B",
                            CatQuestionId = (short)19,
                            EvaOption = "Pionero, explorador, innovador",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 75,
                            Abcd = "C",
                            CatQuestionId = (short)19,
                            EvaOption = "Optimista, ve lo positivo en las cosas",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 76,
                            Abcd = "D",
                            CatQuestionId = (short)19,
                            EvaOption = "Se acomoda, complaciente, listo para ayudar",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 77,
                            Abcd = "A",
                            CatQuestionId = (short)20,
                            EvaOption = "Discutidor, polémico, confrontante",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 78,
                            Abcd = "B",
                            CatQuestionId = (short)20,
                            EvaOption = "Adaptable, flexible",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 79,
                            Abcd = "C",
                            CatQuestionId = (short)20,
                            EvaOption = "Relajado, toma las cosas con calma, tranquilo",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 80,
                            Abcd = "D",
                            CatQuestionId = (short)20,
                            EvaOption = "Ligero, despreocupado, descomplicado",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 81,
                            Abcd = "A",
                            CatQuestionId = (short)21,
                            EvaOption = "Confía en los demás, tiene fe en la gente",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 82,
                            Abcd = "B",
                            CatQuestionId = (short)21,
                            EvaOption = "Contento, satisfecho",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 83,
                            Abcd = "C",
                            CatQuestionId = (short)21,
                            EvaOption = "Positivo, no admite dudas ni temores",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 84,
                            Abcd = "D",
                            CatQuestionId = (short)21,
                            EvaOption = "Pacífico, tranquilo",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 85,
                            Abcd = "A",
                            CatQuestionId = (short)22,
                            EvaOption = "Socialmente hábil, le gusta estar con los demás",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 86,
                            Abcd = "B",
                            CatQuestionId = (short)22,
                            EvaOption = "Educado, culto, conocedor",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 87,
                            Abcd = "C",
                            CatQuestionId = (short)22,
                            EvaOption = "Vigoroso, energético",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 88,
                            Abcd = "D",
                            CatQuestionId = (short)22,
                            EvaOption = "Tolerante, poco estricto, comprensivo",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 89,
                            Abcd = "A",
                            CatQuestionId = (short)23,
                            EvaOption = "Agradable, da gusto estar con él o ella",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 90,
                            Abcd = "B",
                            CatQuestionId = (short)23,
                            EvaOption = "Exacto, correcto, preciso",
                            Value = "C"
                        },
                        new
                        {
                            OptionId = 91,
                            Abcd = "C",
                            CatQuestionId = (short)23,
                            EvaOption = "Tiene opiniones claras, habla libre y abiertamente",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 92,
                            Abcd = "D",
                            CatQuestionId = (short)23,
                            EvaOption = "Reservado, controlado, parco",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 93,
                            Abcd = "A",
                            CatQuestionId = (short)24,
                            EvaOption = "Impaciente, no puede relajarse, no descansa",
                            Value = "D"
                        },
                        new
                        {
                            OptionId = 94,
                            Abcd = "B",
                            CatQuestionId = (short)24,
                            EvaOption = "Sociable, amable",
                            Value = "S"
                        },
                        new
                        {
                            OptionId = 95,
                            Abcd = "C",
                            CatQuestionId = (short)24,
                            EvaOption = "Popular, apreciado por mucha gente",
                            Value = "I"
                        },
                        new
                        {
                            OptionId = 96,
                            Abcd = "D",
                            CatQuestionId = (short)24,
                            EvaOption = "Ordenado, organizado, nítido",
                            Value = "C"
                        });
                });

            modelBuilder.Entity("MAVE.Models.CatQuestion", b =>
                {
                    b.Property<short>("CatQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CatQuestionId"));

                    b.Property<bool>("Initial")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CatQuestionId");

                    b.ToTable("CAT_QUESTION", (string)null);

                    b.HasData(
                        new
                        {
                            CatQuestionId = (short)1,
                            Initial = true,
                            Question = "Amable, gentil"
                        },
                        new
                        {
                            CatQuestionId = (short)2,
                            Initial = true,
                            Question = "Atractivo, simpático, agradable para los demás"
                        },
                        new
                        {
                            CatQuestionId = (short)3,
                            Initial = true,
                            Question = "Fácil de guiar, seguidor"
                        },
                        new
                        {
                            CatQuestionId = (short)4,
                            Initial = true,
                            Question = "Abierto de mente, receptivo"
                        },
                        new
                        {
                            CatQuestionId = (short)5,
                            Initial = true,
                            Question = "Jovial, bromista"
                        },
                        new
                        {
                            CatQuestionId = (short)6,
                            Initial = true,
                            Question = "Competitivo, busca ganar"
                        },
                        new
                        {
                            CatQuestionId = (short)7,
                            Initial = true,
                            Question = "Exigente, difícil de satisfacer"
                        },
                        new
                        {
                            CatQuestionId = (short)8,
                            Initial = true,
                            Question = "Valiente, temerario, lleno de coraje"
                        },
                        new
                        {
                            CatQuestionId = (short)9,
                            Initial = true,
                            Question = "Sociable, disfruta de la compañía de otros"
                        },
                        new
                        {
                            CatQuestionId = (short)10,
                            Initial = true,
                            Question = "De bajo perfil, tibio, reservado"
                        },
                        new
                        {
                            CatQuestionId = (short)11,
                            Initial = true,
                            Question = "Expresivo, habla mucho"
                        },
                        new
                        {
                            CatQuestionId = (short)12,
                            Initial = true,
                            Question = "Refinado, elegante al hablar"
                        },
                        new
                        {
                            CatQuestionId = (short)13,
                            Initial = true,
                            Question = "Agresivo, desafiante, enfocado a la acción"
                        },
                        new
                        {
                            CatQuestionId = (short)14,
                            Initial = true,
                            Question = "Cuidadoso, desconfiado, cauteloso"
                        },
                        new
                        {
                            CatQuestionId = (short)15,
                            Initial = true,
                            Question = "Entusiasta, le pone ganas"
                        },
                        new
                        {
                            CatQuestionId = (short)16,
                            Initial = true,
                            Question = "Tiene autoconfianza, cree en sí mismo, seguro"
                        },
                        new
                        {
                            CatQuestionId = (short)17,
                            Initial = true,
                            Question = "Muy disciplinado, auto controlado"
                        },
                        new
                        {
                            CatQuestionId = (short)18,
                            Initial = true,
                            Question = "Admirable, digno de reconocimiento"
                        },
                        new
                        {
                            CatQuestionId = (short)19,
                            Initial = true,
                            Question = "Respetuoso, trata con consideración a las personas"
                        },
                        new
                        {
                            CatQuestionId = (short)20,
                            Initial = true,
                            Question = "Discutidor, polémico, confrontante"
                        },
                        new
                        {
                            CatQuestionId = (short)21,
                            Initial = true,
                            Question = "Confía en los demás, tiene fe en la gente"
                        },
                        new
                        {
                            CatQuestionId = (short)22,
                            Initial = true,
                            Question = "Socialmente hábil, le gusta estar con los demás"
                        },
                        new
                        {
                            CatQuestionId = (short)23,
                            Initial = true,
                            Question = "Agradable, da gusto estar con él o ella"
                        },
                        new
                        {
                            CatQuestionId = (short)24,
                            Initial = true,
                            Question = "Impaciente, no puede relajarse, no descansa"
                        },
                        new
                        {
                            CatQuestionId = (short)25,
                            Initial = false,
                            Question = "¿Qué tan bien comiste hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)26,
                            Initial = false,
                            Question = "¿Qué tanto ejercicio hiciste hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)27,
                            Initial = false,
                            Question = "¿Descansaste bien anoche (dormiste 8 horas)?"
                        },
                        new
                        {
                            CatQuestionId = (short)28,
                            Initial = false,
                            Question = "¿Qué tan relajado te sentiste hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)29,
                            Initial = false,
                            Question = "¿Leíste algo el día de hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)30,
                            Initial = false,
                            Question = "¿Aprendiste algo nuevo hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)31,
                            Initial = false,
                            Question = "¿Qué tanto socializaste el día de hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)32,
                            Initial = false,
                            Question = "¿Cumpliste con tus tareas de hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)33,
                            Initial = false,
                            Question = "¿Qué tanto te has hidratado el día de hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)34,
                            Initial = false,
                            Question = "¿Qué tan solo te sentiste el día de hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)35,
                            Initial = false,
                            Question = "¿Te comunicaste con un ser querido hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)36,
                            Initial = false,
                            Question = "¿Qué tanto tiempo le dedicaste a tu hobbie hoy?"
                        },
                        new
                        {
                            CatQuestionId = (short)37,
                            Initial = false,
                            Question = "¿Qué tanto tiempo le dedicaste a tus vicios hoy?"
                        });
                });

            modelBuilder.Entity("MAVE.Models.CatRole", b =>
                {
                    b.Property<short>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RoleId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("RoleId");

                    b.ToTable("CAT_ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = (short)1,
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = (short)2,
                            Role = "Admin"
                        },
                        new
                        {
                            RoleId = (short)3,
                            Role = "Psicólogo"
                        },
                        new
                        {
                            RoleId = (short)4,
                            Role = "Usuario"
                        });
                });

            modelBuilder.Entity("MAVE.Models.CatScore", b =>
                {
                    b.Property<short>("ScoreId")
                        .HasColumnType("smallint");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("ScoreId");

                    b.ToTable("CAT_SCORE", (string)null);

                    b.HasData(
                        new
                        {
                            ScoreId = (short)1,
                            ScoreType = "Muy mal"
                        },
                        new
                        {
                            ScoreId = (short)2,
                            ScoreType = "Mal"
                        },
                        new
                        {
                            ScoreId = (short)3,
                            ScoreType = "Regular"
                        },
                        new
                        {
                            ScoreId = (short)4,
                            ScoreType = "Bien"
                        },
                        new
                        {
                            ScoreId = (short)5,
                            ScoreType = "Muy bien"
                        },
                        new
                        {
                            ScoreId = (short)6,
                            ScoreType = "Sí"
                        },
                        new
                        {
                            ScoreId = (short)7,
                            ScoreType = "No"
                        });
                });

            modelBuilder.Entity("MAVE.Models.CatStatus", b =>
                {
                    b.Property<short>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("CAT_STATUS", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = (short)1,
                            Status = "Activo"
                        },
                        new
                        {
                            StatusId = (short)2,
                            Status = "Inactivo"
                        });
                });

            modelBuilder.Entity("MAVE.Models.Mood", b =>
                {
                    b.Property<int>("MoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoodId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<short>("MoodScore")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MoodId");

                    b.HasIndex("UserId");

                    b.ToTable("MOOD", (string)null);
                });

            modelBuilder.Entity("MAVE.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<short>("CatQuestionId")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<short?>("ScoreId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId")
                        .HasName("PK_HABIT");

                    b.HasIndex("CatQuestionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ScoreId");

                    b.HasIndex("UserId");

                    b.ToTable("QUESTION", (string)null);
                });

            modelBuilder.Entity("MAVE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short>("EvaluationId")
                        .HasColumnType("smallint");

                    b.Property<int?>("HealthProfessionalId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("HealthProfessionalId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("USER", null, t =>
                        {
                            t.HasTrigger("DELETE_USER");

                            t.HasTrigger("NEW_USER");

                            t.HasTrigger("UPDATE_USER");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MAVE.Models.Article", b =>
                {
                    b.HasOne("MAVE.Models.CatArticleType", "Type")
                        .WithMany("Articles")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ARTICLE_CAT_ARTICLE_TYPE");

                    b.HasOne("MAVE.Models.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ARTICLE_USER");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAVE.Models.CatOption", b =>
                {
                    b.HasOne("MAVE.Models.CatQuestion", "CatQuestion")
                        .WithMany("CatOptions")
                        .HasForeignKey("CatQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_CAT_OPTION_CAT_QUESTION");

                    b.Navigation("CatQuestion");
                });

            modelBuilder.Entity("MAVE.Models.Mood", b =>
                {
                    b.HasOne("MAVE.Models.User", "User")
                        .WithMany("Moods")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MOOD_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAVE.Models.Question", b =>
                {
                    b.HasOne("MAVE.Models.CatQuestion", "CatQuestion")
                        .WithMany("Questions")
                        .HasForeignKey("CatQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_HABIT_CAT_QUESTION");

                    b.HasOne("MAVE.Models.CatOption", "Option")
                        .WithMany("Questions")
                        .HasForeignKey("OptionId")
                        .HasConstraintName("FK_QUESTION_CAT_OPTION");

                    b.HasOne("MAVE.Models.CatScore", "Score")
                        .WithMany("Questions")
                        .HasForeignKey("ScoreId")
                        .HasConstraintName("FK_QUESTION_CAT_SCORE");

                    b.HasOne("MAVE.Models.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_QUESTION_USER");

                    b.Navigation("CatQuestion");

                    b.Navigation("Option");

                    b.Navigation("Score");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAVE.Models.User", b =>
                {
                    b.HasOne("MAVE.Models.CatEvaluation", "Evaluation")
                        .WithMany("Users")
                        .HasForeignKey("EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_CAT_EVALUATION");

                    b.HasOne("MAVE.Models.User", "HealthProfessional")
                        .WithMany("InverseHealthProfessional")
                        .HasForeignKey("HealthProfessionalId")
                        .HasConstraintName("FK_USER_USER");

                    b.HasOne("MAVE.Models.CatRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_CAT_ROLE");

                    b.HasOne("MAVE.Models.CatStatus", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_USER_CAT_STATUS");

                    b.Navigation("Evaluation");

                    b.Navigation("HealthProfessional");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MAVE.Models.CatArticleType", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("MAVE.Models.CatEvaluation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MAVE.Models.CatOption", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MAVE.Models.CatQuestion", b =>
                {
                    b.Navigation("CatOptions");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MAVE.Models.CatRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MAVE.Models.CatScore", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MAVE.Models.CatStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MAVE.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("InverseHealthProfessional");

                    b.Navigation("Moods");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
